POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MTJlMDM4MDE1Yjc5YTIxNDhlOWI2YWIiLCJpYXQiOjE2MzA0MDYxNTB9.rUvOeFM4nikNagYfKrutw4qaNgY6djYok2MWjH18pSM

{
    "title": "DHllo",
    "author": "ALlowustav Mahler",
    "url": "www.gustavMahler.org",
    "likes": 101111,
    "userId": "611f40304df479096b3e6e41"
}