POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date":"1992-02-02",
    "specialist":"David Solomon",
    "type":"HealthCheck",
    "description":"Broken nose",
    "diagnosisCodes": ["M24.2"],
    "healthCheckRating": 1
}