POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date":"1993-02-02",
    "specialist":"David Gathering",
    "type":"OccupationalHealthcare",
    "description":"Broken jaw",
    "diagnosisCodes": ["M44.2"],
    "employerName": "Jared Diamons",
    "sickLeave": {
        "startDate": "1992-01-01",
        "endDate": "1992-01-02"
    }
}